import jsPDF from 'jspdf';
import type { InvoiceV2 } from '@/types/saas-erp';

interface InvoicePDFData {
  invoice: InvoiceV2;
  companyName?: string;
}

export function generateInvoicePDF({ invoice, companyName }: InvoicePDFData): jsPDF {
  const doc = new jsPDF('p', 'mm', 'a4');
  
  // Header bar
  doc.setFillColor(20, 50, 100);
  doc.rect(0, 0, 210, 38, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('INVOICE', 15, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`No: ${invoice.invoice_number}`, 15, 26);
  doc.text(`Date: ${invoice.issued_at ? new Date(invoice.issued_at).toLocaleDateString() : new Date(invoice.created_at).toLocaleDateString()}`, 15, 32);
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(companyName || 'ezy Logistic HUB', 150, 18, { align: 'right' });
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Logistics ERP System', 150, 24, { align: 'right' });
  
  let y = 50;
  doc.setTextColor(30, 30, 30);

  // Status badge
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  const statusColors: Record<string, [number, number, number]> = {
    Draft: [156, 163, 175],
    Sent: [59, 130, 246],
    Paid: [34, 197, 94],
    Overdue: [239, 68, 68],
    Cancelled: [156, 163, 175],
  };
  const color = statusColors[invoice.status] || [100, 100, 100];
  doc.setTextColor(color[0], color[1], color[2]);
  doc.text(`Status: ${invoice.status.toUpperCase()}`, 195, y, { align: 'right' });
  
  doc.setTextColor(30, 30, 30);
  
  // Shipment details
  y += 5;
  doc.setDrawColor(220, 220, 220);
  doc.line(15, y, 195, y);
  y += 10;
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 50, 100);
  doc.text('SHIPMENT DETAILS', 15, y);
  y += 8;
  
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');

  if (invoice.shipment) {
    const addRow = (label: string, value: string) => {
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text(label, 15, y);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(30, 30, 30);
      doc.text(value, 65, y);
      y += 6;
    };
    
    addRow('Tracking #:', invoice.shipment.tracking_number || '—');
    addRow('Origin:', invoice.shipment.origin);
    addRow('Destination:', invoice.shipment.destination);
    addRow('Status:', invoice.shipment.status);
    if (invoice.shipment.actual_delivery) {
      addRow('Delivered:', new Date(invoice.shipment.actual_delivery).toLocaleDateString());
    }
  } else {
    doc.text('No shipment linked', 15, y);
    y += 6;
  }

  y += 8;
  doc.setDrawColor(220, 220, 220);
  doc.line(15, y, 195, y);
  y += 10;

  // Financial Summary
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 50, 100);
  doc.text('FINANCIAL SUMMARY', 15, y);
  y += 10;

  // Amount box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(15, y, 180, 30, 3, 3, 'F');
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('Total Amount', 25, y + 10);
  
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(20, 50, 100);
  doc.text(`SAR ${Number(invoice.amount).toLocaleString('en', { minimumFractionDigits: 2 })}`, 25, y + 22);
  
  // Due date on right
  if (invoice.due_date) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text('Due Date', 150, y + 10);
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(new Date(invoice.due_date).toLocaleDateString(), 150, y + 18);
  }
  
  y += 40;

  // Payment info
  if (invoice.paid_at) {
    doc.setFillColor(220, 252, 231);
    doc.roundedRect(15, y, 180, 12, 2, 2, 'F');
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(22, 163, 74);
    doc.text(`✓ Paid on ${new Date(invoice.paid_at).toLocaleDateString()}`, 25, y + 8);
    y += 20;
  }

  // Notes
  if (invoice.notes) {
    y += 5;
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(20, 50, 100);
    doc.text('NOTES', 15, y);
    y += 7;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60, 60, 60);
    const lines = doc.splitTextToSize(invoice.notes, 170);
    doc.text(lines, 15, y);
    y += lines.length * 5;
  }

  // Footer
  doc.setFillColor(240, 242, 245);
  doc.rect(0, 282, 210, 15, 'F');
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by ezy Logistic HUB — Invoice ${invoice.invoice_number}`, 15, 289);
  doc.text(new Date().toISOString().split('T')[0], 175, 289);

  return doc;
}

export function downloadInvoicePDF(invoice: InvoiceV2, companyName?: string) {
  const doc = generateInvoicePDF({ invoice, companyName });
  doc.save(`${invoice.invoice_number}.pdf`);
}
