import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useCompany } from './useCompany';
import { toast } from 'sonner';
import type { DpShipment, DpShipmentStatus, DpStatusLog, CreateDpShipmentInput } from '@/types/domestic-pro';

export function useDpShipments(statusFilter?: DpShipmentStatus) {
  const { user } = useAuth();
  const { company } = useCompany();
  const [shipments, setShipments] = useState<DpShipment[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchShipments = useCallback(async () => {
    if (!user || !company) {
      setShipments([]);
      setLoading(false);
      return;
    }

    try {
      let query = supabase
        .from('dp_shipments')
        .select(`
          *,
          origin_warehouse:warehouses!dp_shipments_origin_warehouse_id_fkey(id, name),
          destination_warehouse:warehouses!dp_shipments_destination_warehouse_id_fkey(id, name),
          current_warehouse:warehouses!dp_shipments_current_warehouse_id_fkey(id, name),
          driver:dp_drivers(id, name, phone, vehicle_plate),
          zone:dp_zones(id, name, code),
          shelf:dp_shelves(id, name, code)
        `)
        .eq('company_id', company.id)
        .order('created_at', { ascending: false });

      if (statusFilter) {
        query = query.eq('status', statusFilter);
      }

      const { data, error } = await query;
      if (error) throw error;
      setShipments((data || []) as unknown as DpShipment[]);
    } catch (error) {
      console.error('Error fetching dp shipments:', error);
      toast.error('Failed to load shipments');
    } finally {
      setLoading(false);
    }
  }, [user, company, statusFilter]);

  const createShipment = async (input: CreateDpShipmentInput): Promise<DpShipment | null> => {
    if (!user || !company) return null;
    try {
      const { data, error } = await supabase
        .from('dp_shipments')
        .insert({
          company_id: company.id,
          created_by: user.id,
          barcode: '', // auto-generated by trigger
          ...input,
        })
        .select()
        .single();
      if (error) throw error;
      toast.success(`Shipment created: ${(data as any).barcode}`);
      await fetchShipments();
      return data as DpShipment;
    } catch (error) {
      console.error('Error creating shipment:', error);
      toast.error('Failed to create shipment');
      return null;
    }
  };

  const updateStatus = async (id: string, newStatus: DpShipmentStatus, updates?: Partial<DpShipment>): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('dp_shipments')
        .update({ status: newStatus, ...updates })
        .eq('id', id);
      if (error) throw error;
      toast.success(`Status updated to ${newStatus}`);
      await fetchShipments();
      return true;
    } catch (error: any) {
      console.error('Error updating status:', error);
      toast.error(error.message?.includes('Invalid status') ? error.message : 'Failed to update status');
      return false;
    }
  };

  const updateShipment = async (id: string, updates: Partial<DpShipment>): Promise<boolean> => {
    try {
      const { error } = await supabase.from('dp_shipments').update(updates).eq('id', id);
      if (error) throw error;
      toast.success('Shipment updated');
      await fetchShipments();
      return true;
    } catch (error) {
      console.error('Error updating shipment:', error);
      toast.error('Failed to update shipment');
      return false;
    }
  };

  const deleteShipment = async (id: string): Promise<boolean> => {
    try {
      const { error } = await supabase.from('dp_shipments').delete().eq('id', id);
      if (error) throw error;
      toast.success('Shipment deleted');
      await fetchShipments();
      return true;
    } catch (error) {
      console.error('Error deleting shipment:', error);
      toast.error('Failed to delete shipment');
      return false;
    }
  };

  const getByBarcode = async (barcode: string): Promise<DpShipment | null> => {
    if (!company) return null;
    try {
      const { data, error } = await supabase
        .from('dp_shipments')
        .select('*')
        .eq('company_id', company.id)
        .eq('barcode', barcode)
        .single();
      if (error) throw error;
      return data as DpShipment;
    } catch {
      return null;
    }
  };

  const getStatusLog = async (shipmentId: string): Promise<DpStatusLog[]> => {
    try {
      const { data, error } = await supabase
        .from('dp_shipment_status_log')
        .select('*')
        .eq('shipment_id', shipmentId)
        .order('created_at', { ascending: true });
      if (error) throw error;
      return (data || []) as DpStatusLog[];
    } catch {
      return [];
    }
  };

  useEffect(() => { fetchShipments(); }, [fetchShipments]);

  return {
    shipments,
    loading,
    createShipment,
    updateStatus,
    updateShipment,
    deleteShipment,
    getByBarcode,
    getStatusLog,
    refetch: fetchShipments,
  };
}
