import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useCompany } from './useCompany';
import { toast } from 'sonner';
import type { InvoiceV2, CreateInvoiceInput, InvoiceStatusV2 } from '@/types/saas-erp';

export function useInvoicesV2() {
  const { user } = useAuth();
  const { company } = useCompany();
  const [invoices, setInvoices] = useState<InvoiceV2[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchInvoices = useCallback(async () => {
    if (!user || !company) {
      setInvoices([]);
      setLoading(false);
      return;
    }

    try {
      const { data, error } = await supabase
        .from('invoices_v2')
        .select(`
          *,
          shipment:shipments_v2(*)
        `)
        .eq('company_id', company.id)
        .order('created_at', { ascending: false });

      if (error) throw error;

      setInvoices((data || []) as InvoiceV2[]);
    } catch (error: unknown) {
      console.error('Error fetching invoices:', error);
      toast.error('Failed to load invoices');
    } finally {
      setLoading(false);
    }
  }, [user, company]);

  const createInvoice = async (input: CreateInvoiceInput): Promise<InvoiceV2 | null> => {
    if (!user || !company) {
      toast.error('Company not found');
      return null;
    }

    // Check if shipment is DELIVERED
    const { data: shipment, error: shipmentError } = await supabase
      .from('shipments_v2')
      .select('status')
      .eq('id', input.shipment_id)
      .single();

    if (shipmentError || !shipment) {
      toast.error('Shipment not found');
      return null;
    }

    if (shipment.status !== 'DELIVERED') {
      toast.error('Invoice can only be created for delivered shipments');
      return null;
    }

    try {
      const { data, error } = await supabase
        .from('invoices_v2')
        .insert({
          company_id: company.id,
          shipment_id: input.shipment_id,
          amount: input.amount,
          due_date: input.due_date || null,
          notes: input.notes || null,
          created_by: user.id,
          invoice_number: '', // Auto-generated by trigger
          status: 'Draft',
        })
        .select()
        .single();

      if (error) throw error;

      // Log audit event
      await supabase.rpc('log_audit_event', {
        p_action: 'CREATE',
        p_entity_type: 'invoice',
        p_entity_id: data.id,
        p_new_values: data,
      });

      toast.success(`Invoice ${data.invoice_number} created`);
      await fetchInvoices();
      return data as InvoiceV2;
    } catch (error: unknown) {
      console.error('Error creating invoice:', error);
      toast.error('Failed to create invoice');
      return null;
    }
  };

  const updateInvoiceStatus = async (id: string, status: InvoiceStatusV2): Promise<boolean> => {
    try {
      const updates: Partial<InvoiceV2> = { status };
      
      if (status === 'Sent') {
        updates.issued_at = new Date().toISOString();
      } else if (status === 'Paid') {
        updates.paid_at = new Date().toISOString();
      }

      const { data: oldData } = await supabase
        .from('invoices_v2')
        .select('*')
        .eq('id', id)
        .single();

      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { shipment, ...restUpdates } = updates;

      const { error } = await supabase
        .from('invoices_v2')
        .update(restUpdates)
        .eq('id', id);

      if (error) throw error;

      // Log audit event
      await supabase.rpc('log_audit_event', {
        p_action: 'STATUS_UPDATE',
        p_entity_type: 'invoice',
        p_entity_id: id,
        p_old_values: JSON.parse(JSON.stringify(oldData)),
        p_new_values: JSON.parse(JSON.stringify({ ...oldData, ...restUpdates })),
      });

      toast.success(`Invoice status updated to ${status}`);
      await fetchInvoices();
      return true;
    } catch (error: unknown) {
      console.error('Error updating invoice status:', error);
      toast.error('Failed to update invoice status');
      return false;
    }
  };

  const deleteInvoice = async (id: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('invoices_v2')
        .delete()
        .eq('id', id);

      if (error) throw error;

      toast.success('Invoice deleted');
      await fetchInvoices();
      return true;
    } catch (error: unknown) {
      console.error('Error deleting invoice:', error);
      toast.error('Failed to delete invoice');
      return false;
    }
  };

  const getInvoiceByShipment = (shipmentId: string): InvoiceV2 | undefined => {
    return invoices.find(i => i.shipment_id === shipmentId);
  };

  useEffect(() => {
    fetchInvoices();
  }, [fetchInvoices]);

  return {
    invoices,
    loading,
    createInvoice,
    updateInvoiceStatus,
    deleteInvoice,
    getInvoiceByShipment,
    refetch: fetchInvoices,
  };
}
