import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import type { Invoice, InvoiceItem, InvoiceStatus } from '@/types/erp';

export function useInvoices() {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchInvoices = useCallback(async () => {
    if (!user) return;
    
    try {
      const { data, error } = await supabase
        .from('invoices')
        .select(`
          *,
          customer:customers(*),
          invoice_items(*)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setInvoices((data || []) as Invoice[]);
    } catch (error: unknown) {
      console.error('Error fetching invoices:', error);
      toast.error('Failed to load invoices');
    } finally {
      setLoading(false);
    }
  }, [user]);

  const createInvoice = async (
    invoice: Partial<Invoice>,
    items: Omit<InvoiceItem, 'id' | 'invoice_id' | 'created_at'>[]
  ): Promise<Invoice | null> => {
    if (!user) {
      toast.error('You must be logged in');
      return null;
    }

    try {
      const subtotal = items.reduce((sum, item) => sum + item.total_price, 0);
      const taxAmount = invoice.tax_amount || 0;
      const totalAmount = subtotal + taxAmount;

      // Create invoice - invoice_number is auto-generated by trigger
      const insertData = {
        customer_id: invoice.customer_id || null,
        shipment_id: invoice.shipment_id || null,
        order_id: invoice.order_id || null,
        status: 'Draft' as InvoiceStatus,
        subtotal,
        tax_amount: taxAmount,
        total_amount: totalAmount,
        currency: invoice.currency || 'SAR',
        issue_date: invoice.issue_date || new Date().toISOString().split('T')[0],
        due_date: invoice.due_date || null,
        notes: invoice.notes || null,
        created_by: user.id,
        invoice_number: '', // Will be set by trigger
      };
      
      const { data: invoiceData, error: invoiceError } = await supabase
        .from('invoices')
        .insert(insertData)
        .select()
        .single();

      if (invoiceError) throw invoiceError;

      // Create invoice items
      if (items.length > 0) {
        const invoiceItems = items.map(item => ({
          invoice_id: invoiceData.id,
          description: item.description,
          quantity: item.quantity,
          unit_price: item.unit_price,
          total_price: item.total_price,
        }));

        const { error: itemsError } = await supabase
          .from('invoice_items')
          .insert(invoiceItems);

        if (itemsError) throw itemsError;
      }
      
      toast.success('Invoice created');
      await fetchInvoices();
      return invoiceData as Invoice;
    } catch (error: unknown) {
      console.error('Error creating invoice:', error);
      toast.error('Failed to create invoice');
      return null;
    }
  };

  const updateInvoiceStatus = async (id: string, status: InvoiceStatus): Promise<boolean> => {
    try {
      const updates: Record<string, unknown> = { status };
      
      if (status === 'Paid') {
        updates.paid_date = new Date().toISOString().split('T')[0];
      }

      const { error } = await supabase
        .from('invoices')
        .update(updates)
        .eq('id', id);

      if (error) throw error;
      
      toast.success('Invoice status updated');
      await fetchInvoices();
      return true;
    } catch (error: unknown) {
      console.error('Error updating invoice:', error);
      toast.error('Failed to update invoice');
      return false;
    }
  };

  const deleteInvoice = async (id: string): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('invoices')
        .delete()
        .eq('id', id);

      if (error) throw error;
      
      toast.success('Invoice deleted');
      await fetchInvoices();
      return true;
    } catch (error: unknown) {
      console.error('Error deleting invoice:', error);
      toast.error('Failed to delete invoice');
      return false;
    }
  };

  // Summary stats
  const stats = {
    totalDraft: invoices.filter(i => i.status === 'Draft').length,
    totalSent: invoices.filter(i => i.status === 'Sent').length,
    totalPaid: invoices.filter(i => i.status === 'Paid').length,
    totalOverdue: invoices.filter(i => i.status === 'Overdue').length,
    totalRevenue: invoices
      .filter(i => i.status === 'Paid')
      .reduce((sum, i) => sum + i.total_amount, 0),
    totalOutstanding: invoices
      .filter(i => ['Sent', 'Overdue'].includes(i.status))
      .reduce((sum, i) => sum + i.total_amount, 0),
  };

  useEffect(() => {
    fetchInvoices();
  }, [fetchInvoices]);

  return {
    invoices,
    loading,
    stats,
    createInvoice,
    updateInvoiceStatus,
    deleteInvoice,
    refetch: fetchInvoices,
  };
}
