import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { useCompany } from './useCompany';
import { toast } from 'sonner';
import type { Order, OrderItem, OrderStatus } from '@/types/erp';
import type { Json } from '@/integrations/supabase/types';

export function useOrders() {
  const { user } = useAuth();
  const { company } = useCompany();
  const [orders, setOrders] = useState<Order[]>([]);
  const [loading, setLoading] = useState(true);

  const fetchOrders = useCallback(async () => {
    if (!user || !company) {
      setOrders([]);
      setLoading(false);
      return;
    }
    
    try {
      const { data, error } = await supabase
        .from('orders')
        .select(`
          *,
          customer:customers(*),
          pickup_location:locations!orders_pickup_location_id_fkey(*),
          delivery_location:locations!orders_delivery_location_id_fkey(*),
          order_items(*)
        `)
        .order('created_at', { ascending: false });

      if (error) throw error;
      setOrders((data || []) as Order[]);
    } catch (error: unknown) {
      console.error('Error fetching orders:', error);
      toast.error('Failed to load orders');
    } finally {
      setLoading(false);
    }
  }, [user, company]);

  const createOrder = async (
    order: Partial<Order>,
    items: Omit<OrderItem, 'id' | 'order_id' | 'created_at'>[]
  ): Promise<Order | null> => {
    if (!user || !company) {
      toast.error('You must be logged in with a company');
      return null;
    }

    try {
      // Create order - order_number is auto-generated by trigger
      // We pass empty string, trigger will generate the ORD-XXXXXX number
      const insertData = {
        customer_id: order.customer_id || null,
        pickup_location_id: order.pickup_location_id || null,
        delivery_location_id: order.delivery_location_id || null,
        delivery_address: (order.delivery_address || {}) as Json,
        status: 'Draft' as OrderStatus,
        notes: order.notes || null,
        requested_date: order.requested_date || null,
        created_by: user.id,
        order_number: '',
        company_id: company.id,
      };
      
      const { data: orderData, error: orderError } = await supabase
        .from('orders')
        .insert(insertData)
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      if (items.length > 0) {
        const orderItems = items.map(item => ({
          order_id: orderData.id,
          item_id: item.item_id || null,
          item_name: item.item_name,
          quantity: item.quantity,
          unit: item.unit,
          unit_price: item.unit_price || null,
          notes: item.notes || null,
        }));

        const { error: itemsError } = await supabase
          .from('order_items')
          .insert(orderItems);

        if (itemsError) throw itemsError;
      }
      
      toast.success('Order created');
      await fetchOrders();
      return orderData as Order;
    } catch (error: unknown) {
      console.error('Error creating order:', error);
      toast.error('Failed to create order');
      return null;
    }
  };

  const updateOrderStatus = async (id: string, status: OrderStatus): Promise<boolean> => {
    try {
      const { error } = await supabase
        .from('orders')
        .update({ status })
        .eq('id', id);

      if (error) throw error;
      
      toast.success('Order status updated');
      await fetchOrders();
      return true;
    } catch (error: unknown) {
      console.error('Error updating order:', error);
      toast.error('Failed to update order');
      return false;
    }
  };

  const convertToShipment = async (orderId: string): Promise<{ id: string | null; error?: string }> => {
    if (!user) {
      const msg = 'You must be logged in';
      toast.error(msg);
      return { id: null, error: msg };
    }

    try {
      // Get order details
      const order = orders.find(o => o.id === orderId);
      if (!order) {
        const msg = 'Order not found in local state';
        toast.error(msg);
        return { id: null, error: msg };
      }

      // Create shipment
      const { data: shipment, error: shipmentError } = await supabase
        .from('shipments')
        .insert({
          user_id: user.id,
          order_id: orderId,
          customer_id: order.customer_id,
          status: 'Planned',
        })
        .select()
        .single();

      if (shipmentError) {
        const errorDetails = `Code: ${shipmentError.code}, Message: ${shipmentError.message}, Details: ${shipmentError.details || 'none'}, Hint: ${shipmentError.hint || 'none'}`;
        console.error('Shipment creation error:', shipmentError);
        toast.error(`Shipment error: ${shipmentError.message}`);
        return { id: null, error: errorDetails };
      }

      // Update order status
      await updateOrderStatus(orderId, 'ConvertedToShipment');
      
      toast.success('Order converted to shipment');
      return { id: shipment.id };
    } catch (error: unknown) {
      const err = error as { message?: string; code?: string; details?: string };
      const errorDetails = `${err.message || 'Unknown error'} (code: ${err.code || 'N/A'})`;
      console.error('Error converting order:', error);
      toast.error(`Failed to convert: ${errorDetails}`);
      return { id: null, error: errorDetails };
    }
  };

  useEffect(() => {
    fetchOrders();
  }, [fetchOrders]);

  return {
    orders,
    loading,
    createOrder,
    updateOrderStatus,
    convertToShipment,
    refetch: fetchOrders,
  };
}
